# Cloud Build configuration for importing MeshCentral from GHCR to GCR
# Usage: gcloud builds submit --config=importer.yaml --substitutions=_MESHCENTRAL_VERSION=1.1.56

substitutions:
  _MESHCENTRAL_VERSION: "1.1.56"

steps:
  # 1. Pull from GHCR (GitHub)
  - name: "gcr.io/cloud-builders/docker"
    args: ["pull", "ghcr.io/ylianst/meshcentral:${_MESHCENTRAL_VERSION}"]

  # 2. Tag for GCR (Project-level)
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "tag",
        "ghcr.io/ylianst/meshcentral:${_MESHCENTRAL_VERSION}",
        "gcr.io/$PROJECT_ID/meshcentral:${_MESHCENTRAL_VERSION}",
      ]

  # 3. Push to GCR
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/meshcentral:${_MESHCENTRAL_VERSION}"]

images:
  - "gcr.io/$PROJECT_ID/meshcentral:${_MESHCENTRAL_VERSION}"
